# v1.46.2
run:
  # Avoid false positives on configuration files.
  skip-dirs:
    - resources

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  dupl:
    threshold: 100
  gci:
    sections: [prefix(github.com/lfordyce/tiger)]
  goconst:
    min-len: 10
    min-occurrences: 4
  gocognit:
    min-complexity: 20
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/lfordyce/tiger
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  prealloc:
    # NOTE: since the codebase uses channels as streams pretty extensively, we are
    # disabling the range-over-channel case for this linter.
    range-loops: false

linters:
  enable-all: true
  disable:
    - nlreturn
    - gci
    - gochecknoinits
    - godot
    - godox
    - gomodguard
    - testpackage
    - wsl
    - gomnd
    - goerr113 # most of the errors here are meant for humans
    - goheader
    - exhaustivestruct
    - thelper
    - gocyclo # replaced by cyclop since it also calculates the package complexity
    - maligned # replaced by govet 'fieldalignment'
    - interfacer # deprecated
    - scopelint # deprecated, replaced by exportloopref
    - golint # this linter is deprecated
    - ireturn
    - tagliatelle
    - promlinter
  fast: false