version: "3"
services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    volumes:
      - ${PWD}/resources/docker/src/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${PWD}/resources/docker/src/data:/var/lib/postgresql/csvs
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    command: ["postgres", "-c", "log_statement_stats=on"]
    environment:
      POSTGRES_DB: homework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "homework" ]
      interval: 3s
      timeout: 3s
      retries: 5
volumes:
  data: